language: c
sudo: false

matrix:
  include:
    - os: linux
      dist: trusty
      compiler: gcc
      addons:
        apt:
          sources: [ 'ubuntu-toolchain-r-test' ]
          packages: [ 'intltool', 'gcc-7' ]
      env:
        - MATRIX_EVAL="CC=gcc-7 && CFLAGS='-fno-omit-frame-pointer -fsanitize=undefined -fsanitize=address -ggdb3 -fvar-tracking-assignments -Og'"

    - os: linux
      dist: trusty
      compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-trusty-4.0']
          packages: [ 'intltool', 'clang-4.0']
      env:
        - MATRIX_EVAL="CC=clang-4.0 && CFLAGS='-fno-omit-frame-pointer -fsanitize=undefined -fsanitize=address -ggdb3 -fvar-tracking-assignments -Og'"

script:
  - eval "${MATRIX_EVAL}"
  - ./autogen.sh && ./configure --without-libsystemd --disable-man && make -j2 && make -j2 -k check

after_failure:
  - cat config.log
